#!/bin/bash

PROGNAME="${0##*/}"

usage() {
  echo -e "usage: $PROGNAME DIRECTORY..." >&2
  exit 1
}

[[ "$#" -eq 0 ]] && usage

generate() {
  openssl genrsa \
    -out "$1/private.key" 2048

  openssl rsa \
    -in "$1/private.key" \
    -outform PEM \
    -pubout \
    -out "$1/public.pem"
}

while [[ "$#" > 0 ]]; do
  if [[ -d "$1" ]]; then
    generate $1
  else
    echo "invalid directory $(realpath $1)"
  fi
  shift
done
